[package]
name = "quantswepeer"
version = "1.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
codegen-units = 1

[dependencies]
wasm-bindgen = "0.2"
fastrand = "2.0"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }